// <auto-generated />
namespace QuanLyNhanSu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class qlimga2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qlimga2));
        
        string IMigrationMetadata.Id
        {
            get { return "202112030425597_qlimga2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
