// <auto-generated />
namespace QuanLyNhanSu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class creat_table_PBRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creat_table_PBRole));
        
        string IMigrationMetadata.Id
        {
            get { return "202110100529034_creat_table_PB.Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
